### ISSUE TITLE
Allow configuration of the library with application.yaml

### ISSUE THREAD

**Issue by milanov** [gasparbarancelli/spring-native-query#12]
We're using application.yaml to configure our project, not application.properties. This took me a while to figure out, as i was adding my spring native config in the yaml file and it didn't get picked up. The only way to get it running is to add an application.properties file, along with the yaml one, but that is not a viable solution. Could the configuration reading be modified to read the yaml file as well?

**Comment by rafaeldalbosco** [comment]
Hi @milanov this library supports reading of YAML configuration file. Try to use:
```
native-query:
  package-scan: com.your.package
```

**Comment by milanov** [comment]
Yes, but that's in another file, `bootstrap.yaml`, not `application.yaml`. See https://github.com/gasparbarancelli/spring-native-query/blob/master/src/main/java/io/github/gasparbarancelli/PropertyUtil.java#L28.

**Comment by gasparbarancelli** [comment]
Now the properties are searched for in the following files: application.properties, bootstrap.properties, application.yaml, application.yml, bootstrap.yaml, bootstrap.yml

I just published version 1.0.12. It takes a few hours to become available.

**Comment by milanov** [comment]
If that's not responsiveness, I don't know what it. Very kind regards.
