### ISSUE TITLE
Escaping arguments from a list of values

### ISSUE THREAD

**Issue by milanov** [gasparbarancelli/spring-native-query#13]
One of the reasons we're looking into using the spring native query library is to move away from manually concatenating strings in order to execute a native query. However, we're now running into a problem related to using a list of parameters:
```
SELECT id, x, y, z
FROM table
WHERE  active = :pActive
/* for token in pTokens */
AND func(field1) LIKE func('{{ token }}') OR func(field2) LIKE func('{{ token }}')
/* endfor */
```

Written like this we're open to an SQL injection, since the tokens are not properly escaped. However i couldn't come up with a way to achieve that using named parameters. The only solution  i've applied in the past is to use positional arguments where `{{token}}` is used, which works, but i don't know if it's currently supported.

**Comment by gasparbarancelli** [comment]
We can solve your problem as follows. 
Adding a map as a parameter.
``` java
@NativeQueryParam ("parameters") Map <String, Object> parameters;
```

In your sql file, we go through the map keys and add it as a parameter name.
``` sql
SELECT id, x, y, z
FROM table
WHERE active =: pActive
/ * for key, value in parameters * /
AND func (field1) LIKE func (: / * key * /) OR func (field2) LIKE func (: / * key * /)
/ * endfor * /
```

In the query, I can go through the map and add the parameters.
``` java
parametros.forEach ((key, value) -> {
     query.setParameter (p.getName (), p.getValue ());
});
```
What do you think?

**Comment by milanov** [comment]
I think this would be a very nice solution, generic enough to cover both a map use case + our list case (where we'd have to generate some keys for the values but that would be easily done with some indexes).

**Comment by gasparbarancelli** [comment]
Could you give me a new example? We will try to solve your problem.

**Comment by milanov** [comment]
Well not really a new one, but i can give more context. We need to split a search token based on some rules and then search for a match in a bunch of fields:
```
List<String> tokens = Tokenizer.tokenize(searchInput).stream()
.map(token -> "%" + token + "%").collect(toList());
var results = nativeRepository.findAll(paramObject, tokens, pageable);
```

The `paramObject` we've annotated with `@NativeQueryParam(value = "p", addChildren = true) ParamObject params`. However for the list of token strings there's just `@NativeQueryParam(value = "pTokens") List<String> tokens`. And from then on we're onto the initial problem about the lack of escaping. Your proposed solution work work, as we'll convert the `List<String> tokens` into a map rather easily - `IntStream.range(0, tokens.size()).boxed().collect(toMap(i -> "p" + i, tokens::get))`.

**Comment by gasparbarancelli** [comment]
I believe that the best solution is using a map. I will implement the parameters by map, I hope to release this new version today.

**Comment by gasparbarancelli** [comment]
Version 1.0.14 released.
Add an example on github.
https://github.com/gasparbarancelli/demo-spring-native-query
