### ISSUE TITLE
Configure the library programatically

### ISSUE THREAD

**Issue by milanov** [gasparbarancelli/spring-native-query#15]
**Is your feature request related to a problem? Please describe.**
We're presenting our customer with the application.yaml file, so they can configure their environment as they wish. Some internal details, however, we prefer not to expose to them. This is the case when using this library, because we export the `native-query` options.

**Describe the solution you'd like**
An option where we can programatically set the `native-query` options.

**Describe alternatives you've considered**
Well, we can always tell the customer to always include that option, won't be the end of the world.

**Comment by gasparbarancelli** [comment]
We can also define programatically implementing the interface NativeQueryConfig.

``` java
import io.github.gasparbarancelli.NativeQueryConfig;
public class NativeQueryDefaultConfig implements NativeQueryConfig {
    @Override
    public String getPackageScan() {
        return "io.github.gasparbarancelli.demospringnativequery";
    }
    @Override
    public String getFileSufix() {
        return "sql";
    }
}
```
