### ISSUE TITLE
Sorting not working on fields whose name differs than their underlying column name

### ISSUE THREAD

**Issue by milanov** [gasparbarancelli/spring-native-query#16]
**Describe the bug**
Well, first of all I'm sorry for creating you that much work :) The bug is related to sorting, when a field name is passed, but it's not the same as the underlying column name.

**To Reproduce**
* Have an entity with a field that is annotated with `@Column(name = "field_name")`, when the field itself is called differently - `private String fieldName;`. Then passing this as a `Sort` parameter leads to an incorrect SQL query, as it tries to filter by `fieldName`, not `field_name`.

**Expected behavior**
Sorting should work, as it works with a regular spring data repository.

**Comment by gasparbarancelli** [comment]
In native queries you need to pass the database column name. If it was a JPA query with the class property name it would work.

**Comment by milanov** [comment]
Okay, i understand. I solved the issue by just adding a simple check for a sort param in the sql, as we sort by just one field. Considering the issue solved on my side.
