### ISSUE TITLE
NullPointerException during programatically configuring the library

### ISSUE THREAD

**Issue by milanov** [gasparbarancelli/spring-native-query#17]
**Describe the bug**
The `PropertyUtil#getYamlValue` throws a null pointer exception if there is no `native-query` configuration in the yaml file:
```
Map<String, String> map = (HashMap<String, String>) obj.get("native-query");
return Optional.ofNullable(map.get(propertyName.replace("native-query.", "")));
```

**To Reproduce**
Try to define a class to configure a class that extends `NativeQueryConfig`, but don't include any `native-query` configuration in an existing yaml file.

**Expected behavior**
It should work without having to include any configuration in the properties file.

**Comment by gasparbarancelli** [comment]
I released a new version of the library, update it!
